version: '3.8'

services:
    web:
        build:
            context: .
            network: bridge
        ports: 
            - 5000:5000
        volumes:
            - .:/app
    
    redis:
        image: "redis:latest"
        ports:
            - 6380:6379
        volumes:
            - redis-data:/data
        command: >
          sh -c '
            mkdir -p /usr/local/etc/redis &&
            echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
            echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
            echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
            redis-server /usr/local/etc/redis/redis.conf
          '
        restart: unless-stopped

volumes:
    redis-data: