name: CI
on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
    docker:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      services:
        redis:
          image: redis:7-alpine
          ports:
            - 6379:6379
          options: >-
            --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
      steps:
        - uses: actions/checkout@v4

        - name: Installing packages from requirements.txt
          run: pip install -r requirements.txt
        
        - name: Running pytest
          run: pytest
          env:
            redis_host: localhost

        - name: Login to GitHub Container Registry
          if: success()
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push Docker image
          if: success()
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: ghcr.io/barden-dev/testflaskdocker:latest
        
